//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmsmacar_model
    {
        public string model_uid { get; set; }
        public string model_code { get; set; }
        public string model_name { get; set; }
        public Nullable<decimal> max_kgs { get; set; }
        public Nullable<decimal> max_cbm { get; set; }
        public string remark { get; set; }
        public string is_inactive { get; set; }
        public decimal voided { get; set; }
        public string rec_crt_user { get; set; }
        public string rec_upd_user { get; set; }
        public Nullable<System.DateTime> rec_crt_date { get; set; }
        public Nullable<System.DateTime> rec_upd_date { get; set; }
        public decimal rpt_seq { get; set; }
        public string type { get; set; }
        public decimal cntr_weight { get; set; }
        public string size_type { get; set; }
    }
}
